# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Avans ATGM"
description: ATGM
email: es.rasche@avans.nl
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://avans-atgm.github.io" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username:
github_username:  avans-atgm
blurb: ""
sass:
  sass_dir: assets/css

# Build settings
markdown: kramdown
kramdown:
  toc_levels: 1..2

scholar:
  style: bioinformatics
  group_by: year
  order: descending
  sort_by: year
  group_order: descending

citation:
    citation_style: apa
    citation_locale: en

# Requires new release of jekyll_analytics
#jekyll_analytics:
  #Plausible:
    #domain: 'galaxyproject.eu'   # The domain configured in plausible
    #source: 'https://plausible.galaxyproject.eu/js/plausible.js' # The source of the javascript

team_sites: {}

header_links:
    main:
        - name: News
          url: /news
        - name: Events
          url: /events
        - name: People
          url: /people
        #- name: Citations
          #url: /citations
        - name: Tools
          url: /tools
        - name: About
          url: /about

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - .idea/
#
# This will simultaneously render all collection items as "plain" pages
collections:
  posts:
    permalink: /posts/:year/:month/:day/:title/
  posts_plain:
    permalink: /posts/:year/:month/:day/:title/plain.html
    output: true
  events:
    permalink: /event/:path/
    output: true
  events_ical:
    permalink: /event/:path/event.ics
    output: true
  events_plain:
    permalink: /event/:path/plain.html
    output: true

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: news
  -
    scope:
      path: "_posts_plain"
    values:
      layout: news-galaxy
  -
    scope:
      path: "_events"
    values:
      layout: event
  -
    scope:
      path: "_events_ical"
    values:
      layout: event-ical
  -
    scope:
      path: "_events_plain"
    values:
      layout: event-galaxy
