---
tags: [training]
title: Training Biologische databases 05-12
starts: 2022-12-05
ends: 2022-12-05
organiser:
  name: Donny Vrins
  email: Dl.vrins@avans.nl
location: Avans Hogeschool LD323
---

To join the Tiaas class training for that day please click on this link https://galaxy.atgm.avans.nl/join-training/bio-db-5-12